apiVersion: v1
kind: ConfigMap
metadata:
  name: fineractmysql-initdb
  labels:
    app: fineract-server
data:
  init.sql: |
    # create databases
    CREATE DATABASE IF NOT EXISTS `fineract_tenants`;
    CREATE DATABASE IF NOT EXISTS `fineract_default`;

    # create root user and grant rights
    GRANT ALL ON *.* TO 'root'@'%';
