apiVersion: v1
kind: PersistentVolume            # Create a PersistentVolume
metadata:
  name: mariadb-pv
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    fsType: ext4
    pdName: apache-fineract-pd

---
apiVersion: v1
kind: PersistentVolumeClaim      # Create a PersistentVolumeClaim to request a PersistentVolume storage
metadata:
  name: mariadb-pv-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-cluster
  namespace: default
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-cluster
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - image: mariadb:10.6
          imagePullPolicy: IfNotPresent
          name: mariadb
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: mysql
          livenessProbe:
            exec:
              command:
                - mysql
                - --help
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
          # readinessProbe:
          #   exec:
          #     command:
          #       - mysql -u root -p mysql h 127.0.0.1 -e SELECT 1
          #     initialDelaySeconds: 10
          #     periodSeconds: 10
          #     timeoutSeconds: 1
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql
              subPath: mysql
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-pv-claim