apiVersion: apps/v1
kind: Deployment
metadata:
  name: latam-mifos
  labels:
    app: latam-mifos
spec:
  selector:
    matchLabels:
      app: latam-mifos
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: latam-mifos
        tier: frontend
    spec:
      initContainers:
        - name: init-myservice
          image: busybox:1.28
          command: ['sh', '-c', 'echo -e "Checking for the availability of Fineract server deployment"; while ! nc -z "fineract-server" 8443; do sleep 1; printf "-"; done; echo -e " >> Fineract server has started";']
      containers:
        - name: latam-mifos
          image: leonardohildt/mifos-app:2022-12-29--27-37
          resources:
            limits:
              cpu: "1000m"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "0.5Gi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 90
            periodSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 90
            periodSeconds: 1
          ports:
            - containerPort: 80
              name: latam-mifos
