apiVersion: v1
kind: Service
metadata:
  labels:
    app: latam-mifos-community
  name: latam-mifos-community
spec:
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 80
  selector:
    app: latam-mifos-community
    tier: frontend
  type: LoadBalancer