apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fineract-server
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/leomax060778/community-app-config.git
    targetRevision: HEAD
    path: backend/base
  destination:
    server: https://kubernetes.default.svc
    namespace: fineract-server

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true